spring:
  # Configuração H2 (banco em memória)
  datasource:
    url: jdbc:h2:mem:drivermanager
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # Configuração alternativa PostgreSQL local
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/drivermanager
  #   driver-class-name: org.postgresql.Driver
  #   username: postgres
  #   password: postgres

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.fretemais.challenge.drivermanager: DEBUG
    org.springframework.security: DEBUG
